//! Frontend build script
//!
//! Read backend configuration at compile time and embed it into frontend binary.
//! This ensures frontend and backend share the same configuration.

use common::config::AppConfig;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=../.ai_orz/ai_orz.toml");
    println!("cargo:rerun-if-changed=../common/config/ai_orz.toml");
    println!("cargo:rerun-if-changed=styles/input.css");
    println!("cargo:rerun-if-changed=package.json");
    println!("cargo:rerun-if-changed=package-lock.json");

    compile_tailwind()?;

    let config_path = Path::new("../.ai_orz/ai_orz.toml");

    let config_content = if config_path.exists() {
        fs::read_to_string(config_path)?
    } else {
        let default_config = include_str!("../common/config/ai_orz.toml");
        default_config.to_string()
    };

    let config: AppConfig = toml::from_str(&config_content)?;

    let config_json = serde_json::to_string_pretty(&config)?;

    let generated_code = format!(
        "// Generated compile-time configuration from build.rs\n\
        // DO NOT EDIT - This file is automatically generated by build.rs\n\n\
        use common::config::AppConfig;\n\n\
        /// Static configuration embedded at compile time from backend config file\n\
        pub static COMPILED_CONFIG: &str = r###\"{config_json}\"###;\n\n\
        /// Get the parsed configuration at runtime\n\
        pub fn get_config() -> AppConfig {{\n\
            serde_json::from_str(COMPILED_CONFIG).expect(\"Failed to parse compiled config\")\n\
        }}\n"
    );

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("compiled_config.rs");
    fs::write(out_path, generated_code)?;

    Ok(())
}

fn compile_tailwind() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let input = Path::new(&manifest_dir).join("styles/input.css");
    let output = Path::new(&manifest_dir).join("public/output.css");
    let node_modules_bin = Path::new(&manifest_dir).join("node_modules/.bin/tailwindcss");
    let node_modules_dir = Path::new(&manifest_dir).join("node_modules");

    if !input.exists() {
        return Ok(());
    }

    fs::create_dir_all(Path::new(&manifest_dir).join("public"))?;

    if !node_modules_bin.exists() {
        if node_modules_dir.exists() {
            println!(
                "cargo:warning=node_modules exists but tailwindcss binary not found, trying npm install..."
            );
        } else {
            println!("cargo:warning=node_modules not found, running npm install...");
        }
        let npm_status = Command::new("npm")
            .arg("install")
            .current_dir(&manifest_dir)
            .status();
        match npm_status {
            Ok(s) if s.success() => {}
            Ok(s) => {
                println!(
                    "cargo:warning=npm install failed with status: {}, skipping CSS build",
                    s
                );
                return Ok(());
            }
            Err(e) => {
                println!("cargo:warning=npm not found ({}), skipping CSS build", e);
                return Ok(());
            }
        }
    }

    if !node_modules_bin.exists() {
        println!(
            "cargo:warning=tailwindcss binary still not found after npm install, skipping CSS build"
        );
        return Ok(());
    }

    let status = Command::new(&node_modules_bin)
        .arg("-i")
        .arg(&input)
        .arg("-o")
        .arg(&output)
        .arg("--minify")
        .current_dir(&manifest_dir)
        .status();

    match status {
        Ok(s) if s.success() => {
            println!("cargo:warning=Tailwind CSS compiled successfully");
        }
        Ok(s) => {
            println!(
                "cargo:warning=Tailwind CSS compilation exited with status: {}",
                s
            );
        }
        Err(e) => {
            println!("cargo:warning=Failed to run tailwindcss: {}", e);
        }
    }

    Ok(())
}
