//! Frontend build script
//!
//! Read backend configuration at compile time and embed it into frontend binary.
//! This ensures frontend and backend share the same configuration.

use common::config::AppConfig;
use std::fs;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Tell cargo to rerun build script only when config file changes
    println!("cargo:rerun-if-changed=../ai_orz.toml");
    println!("cargo:rerun-if-changed=../common/config/ai_orz.toml");

    // Load configuration from the project root
    let config_path = Path::new("../ai_orz.toml");

    let config_content = if config_path.exists() {
        // Use existing config if it exists
        fs::read_to_string(config_path)?
    } else {
        // Fallback to default embedded config from common
        let default_config = include_str!("../common/config/ai_orz.toml");
        default_config.to_string()
    };

    // Parse config using common type
    let config: AppConfig = toml::from_str(&config_content)?;

    // Serialize config to JSON and write to a Rust file that can be imported by frontend
    let config_json = serde_json::to_string_pretty(&config)?;

    // Generate a Rust module containing the static config
    let generated_code = format!(
        "// Generated compile-time configuration from build.rs\n\
        // DO NOT EDIT - This file is automatically generated by build.rs\n\n\
        use common::config::AppConfig;\n\n\
        /// Static configuration embedded at compile time from backend config file\n\
        pub static COMPILED_CONFIG: &str = r###\"{config_json}\"###;\n\n\
        /// Get the parsed configuration at runtime\n\
        pub fn get_config() -> AppConfig {{\n\
            serde_json::from_str(COMPILED_CONFIG).expect(\"Failed to parse compiled config\")\n\
        }}\n"
    );

    // Write to OUT_DIR for import by main code
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("compiled_config.rs");
    fs::write(out_path, generated_code)?;

    println!("cargo:warning=Embedded backend configuration into frontend at compile time");

    Ok(())
}
