//! Frontend build script
//!
//! Read backend configuration at compile time and embed it into frontend binary.
//! This ensures frontend and backend share the same configuration.

use common::config::AppConfig;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=../.ai_orz/ai_orz.toml");
    println!("cargo:rerun-if-changed=../common/config/ai_orz.toml");
    println!("cargo:rerun-if-changed=styles/input.css");
    println!("cargo:rerun-if-changed=package.json");
    println!("cargo:rerun-if-changed=package-lock.json");

    compile_tailwind()?;
    copy_docs()?;

    let config_path = Path::new("../.ai_orz/ai_orz.toml");

    let config_content = if config_path.exists() {
        fs::read_to_string(config_path)?
    } else {
        let default_config = include_str!("../common/config/ai_orz.toml");
        default_config.to_string()
    };

    let config: AppConfig = toml::from_str(&config_content)?;

    let config_json = serde_json::to_string_pretty(&config)?;

    let generated_code = format!(
        "// Generated compile-time configuration from build.rs\n\
        // DO NOT EDIT - This file is automatically generated by build.rs\n\n\
        use common::config::AppConfig;\n\n\
        /// Static configuration embedded at compile time from backend config file\n\
        pub static COMPILED_CONFIG: &str = r###\"{config_json}\"###;\n\n\
        /// Get the parsed configuration at runtime\n\
        pub fn get_config() -> AppConfig {{\n\
            serde_json::from_str(COMPILED_CONFIG).expect(\"Failed to parse compiled config\")\n\
        }}\n"
    );

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("compiled_config.rs");
    fs::write(out_path, generated_code)?;

    Ok(())
}

/// 确定性短 ID：基于路径字符串的 128-bit 哈希
/// 将任意长路径映射为固定长度的十六进制字符串，避免文件系统路径超长（>256 字符）
fn short_id(rel: &str) -> String {
    let mut h: u128 = 5381;
    for b in rel.bytes() {
        h = h.wrapping_mul(31).wrapping_add(b as u128);
    }
    format!("{:032x}", h)
}

/// 文档中心静态资源：将仓库 docs/ 中的核心文档复制到 public/docs/，
/// 并生成目录清单 index.json 供前端文档中心页面运行时 fetch。
///
/// 所有文档文件统一使用 [`short_id`] 生成的哈希短路径存储，
/// 避免深嵌套目录名导致的路径超长问题。
/// 原始标题和目录结构仅用于前端 UI 展示。
///
/// 收录范围：
/// - docs/ 根目录的纲要文档（路径短，保留原名）
/// - docs/wiki/knowledge/zh/（知识卡片，层级结构 → 哈希路径）
/// - docs/wiki/zh/content/（代码 Wiki，层级结构 → 哈希路径）
/// - docs/design/、docs/plan/、docs/archive/（扁平列表 → 哈希路径）
fn copy_docs() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let docs_src = Path::new(&manifest_dir).join("../docs");
    if !docs_src.exists() {
        println!("cargo:warning=docs/ not found, skipping docs center copy");
        return Ok(());
    }

    let dest_root = Path::new(&manifest_dir).join("public/docs");
    if dest_root.exists() {
        fs::remove_dir_all(&dest_root)?;
    }
    fs::create_dir_all(&dest_root)?;

    let mut sections: Vec<serde_json::Value> = Vec::new();

    // ---- 分区 1：总览（根目录纲要文档，路径短无需哈希）----
    {
        let root_docs: &[(&str, &str)] = &[
            ("README.md", "项目概览"),
            ("ARCHITECTURE.md", "架构总纲"),
            ("LAYERED_ARCHITECTURE_PRACTICE.md", "分层架构实践"),
            ("CODE_WIKI.md", "代码认知入口"),
            ("memory_design.md", "记忆系统设计"),
        ];
        let mut overview_docs: Vec<serde_json::Value> = Vec::new();
        for (file, title) in root_docs {
            let src = docs_src.join(file);
            if src.exists() {
                fs::copy(&src, dest_root.join(file))?;
                println!("cargo:rerun-if-changed={}", src.display());
                overview_docs.push(serde_json::json!({ "title": title, "path": file }));
            }
        }
        if !overview_docs.is_empty() {
            sections.push(serde_json::json!({ "label": "总览", "docs": overview_docs }));
        }
    }

    // ---- 分区 2 & 3：层级目录型文档（知识卡片 + 代码 Wiki）----
    // 统一使用哈希短路径：文件存为 {dest_prefix}/{hash}.md，目录结构仅用于 JSON 分组展示
    {
        /// 层级目录树节点
        enum DocNode {
            File {
                title: String,
                short_path: String,
            },
            Dir {
                name: String,
                children: Vec<DocNode>,
            },
        }

        fn walk_dir_hierarchical(
            dir: &Path,
            base: &Path,
            dest_root: &Path,
            dest_prefix: &str,
        ) -> std::io::Result<Vec<DocNode>> {
            let mut nodes = Vec::new();
            let mut paths: Vec<std::path::PathBuf> = fs::read_dir(dir)?
                .filter_map(|e| e.ok().map(|e| e.path()))
                .collect();
            paths.sort();
            for path in paths {
                if path.is_dir() {
                    let name = path
                        .file_name()
                        .map(|s| s.to_string_lossy().to_string())
                        .unwrap_or_default();
                    let children = walk_dir_hierarchical(&path, base, dest_root, dest_prefix)?;
                    if !children.is_empty() {
                        nodes.push(DocNode::Dir { name, children });
                    }
                } else if path.extension().is_some_and(|ext| ext == "md")
                    && let Ok(rel) = path.strip_prefix(base)
                {
                    let rel_str = rel.to_string_lossy().replace('\\', "/");
                    let sid = short_id(&rel_str);
                    let short_path = format!("{}/{}.md", dest_prefix, sid);
                    let dest = dest_root.join(&short_path);
                    if let Some(parent) = dest.parent() {
                        let _ = fs::create_dir_all(parent);
                    }
                    let _ = fs::copy(&path, &dest);
                    println!("cargo:rerun-if-changed={}", path.display());
                    let stem = Path::new(&rel_str)
                        .file_stem()
                        .map(|s| s.to_string_lossy().to_string())
                        .unwrap_or_else(|| rel_str.clone());
                    nodes.push(DocNode::File {
                        title: stem,
                        short_path,
                    });
                }
            }
            Ok(nodes)
        }

        fn node_to_json(node: &DocNode) -> serde_json::Value {
            match node {
                DocNode::File { title, short_path } => {
                    serde_json::json!({ "title": title, "path": short_path })
                }
                DocNode::Dir { name, children } => {
                    let children_json: Vec<serde_json::Value> =
                        children.iter().map(node_to_json).collect();
                    serde_json::json!({ "label": name, "children": children_json })
                }
            }
        }

        // 分区 2：知识卡片
        let knowledge_src = docs_src.join("wiki/knowledge/zh");
        if knowledge_src.is_dir() {
            let tree =
                walk_dir_hierarchical(&knowledge_src, &docs_src, &dest_root, "wiki/knowledge")?;
            if !tree.is_empty() {
                let groups: Vec<serde_json::Value> = tree.iter().map(node_to_json).collect();
                sections.push(serde_json::json!({
                    "label": "知识卡片",
                    "groups": groups
                }));
            }
        }

        // 分区 3：代码 Wiki
        let wiki_src = docs_src.join("wiki/zh/content");
        if wiki_src.is_dir() {
            let tree = walk_dir_hierarchical(&wiki_src, &docs_src, &dest_root, "wiki/wiki")?;
            if !tree.is_empty() {
                let groups: Vec<serde_json::Value> = tree.iter().map(node_to_json).collect();
                sections.push(serde_json::json!({
                    "label": "代码 Wiki",
                    "groups": groups
                }));
            }
        }
    }

    // ---- 分区 4：其他文档（design + plan + archive，扁平列表 + 哈希短路径）----
    {
        let mut other_docs: Vec<serde_json::Value> = Vec::new();
        for dir_name in ["design", "plan", "archive"] {
            let src_dir = docs_src.join(dir_name);
            if !src_dir.is_dir() {
                continue;
            }
            let mut stack = vec![src_dir];
            while let Some(current) = stack.pop() {
                for entry in fs::read_dir(&current)? {
                    let entry = entry?;
                    let path = entry.path();
                    if path.is_dir() {
                        stack.push(path);
                    } else if path.extension().is_some_and(|ext| ext == "md")
                        && let Ok(rel) = path.strip_prefix(&docs_src)
                    {
                        let rel_str = rel.to_string_lossy().replace('\\', "/");
                        let sid = short_id(&rel_str);
                        let short_path = format!("other/{}.md", sid);
                        let dest = dest_root.join(&short_path);
                        if let Some(parent) = dest.parent() {
                            let _ = fs::create_dir_all(parent);
                        }
                        let _ = fs::copy(&path, &dest);
                        println!("cargo:rerun-if-changed={}", path.display());
                        let stem = Path::new(&rel_str)
                            .file_stem()
                            .map(|s| s.to_string_lossy().to_string())
                            .unwrap_or_else(|| rel_str.clone());
                        let display_title = format!("{}/{}", dir_name, stem);
                        other_docs.push(serde_json::json!({
                            "title": display_title,
                            "path": short_path
                        }));
                    }
                }
            }
        }
        if !other_docs.is_empty() {
            other_docs.sort_by(|a, b| {
                a.get("title")
                    .and_then(|v| v.as_str())
                    .cmp(&b.get("title").and_then(|v| v.as_str()))
            });
            sections.push(serde_json::json!({ "label": "其他文档", "docs": other_docs }));
        }
    }

    let index = serde_json::json!({ "sections": sections });
    let index_json = serde_json::to_string_pretty(&index)?;
    fs::write(dest_root.join("index.json"), index_json)?;

    Ok(())
}

fn compile_tailwind() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let input = Path::new(&manifest_dir).join("styles/input.css");
    let output = Path::new(&manifest_dir).join("public/output.css");
    let node_modules_bin = Path::new(&manifest_dir).join("node_modules/.bin/tailwindcss");
    let node_modules_dir = Path::new(&manifest_dir).join("node_modules");

    if !input.exists() {
        return Ok(());
    }

    fs::create_dir_all(Path::new(&manifest_dir).join("public"))?;

    if !node_modules_bin.exists() {
        if node_modules_dir.exists() {
            println!(
                "cargo:warning=node_modules exists but tailwindcss binary not found, trying npm install..."
            );
        } else {
            println!("cargo:warning=node_modules not found, running npm install...");
        }
        let npm_status = Command::new("npm")
            .arg("install")
            .current_dir(&manifest_dir)
            .status();
        match npm_status {
            Ok(s) if s.success() => {}
            Ok(s) => {
                println!(
                    "cargo:warning=npm install failed with status: {}, skipping CSS build",
                    s
                );
                return Ok(());
            }
            Err(e) => {
                println!("cargo:warning=npm not found ({}), skipping CSS build", e);
                return Ok(());
            }
        }
    }

    if !node_modules_bin.exists() {
        println!(
            "cargo:warning=tailwindcss binary still not found after npm install, skipping CSS build"
        );
        return Ok(());
    }

    let status = Command::new(&node_modules_bin)
        .arg("-i")
        .arg(&input)
        .arg("-o")
        .arg(&output)
        .arg("--minify")
        .current_dir(&manifest_dir)
        .status();

    match status {
        Ok(s) if s.success() => {
            println!("cargo:warning=Tailwind CSS compiled successfully");
        }
        Ok(s) => {
            println!(
                "cargo:warning=Tailwind CSS compilation exited with status: {}",
                s
            );
        }
        Err(e) => {
            println!("cargo:warning=Failed to run tailwindcss: {}", e);
        }
    }

    Ok(())
}
