[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[build-dependencies]
common = { path = "../common" }
toml = "0.8"
serde_json = "1.0"

[dependencies]
dioxus = { version = "0.7.9", features = ["web", "router"] }
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
web-sys = { version = "0.3.103", features = ["Window", "Performance", "Storage", "EventSource", "MessageEvent", "Event", "Request", "RequestInit", "RequestCredentials", "Response", "FormData", "HtmlInputElement", "FileList", "File", "Blob", "BlobPropertyBag", "HtmlElement", "Navigator", "Clipboard", "MediaQueryList", "MediaQueryListEvent", "HtmlCanvasElement", "CanvasRenderingContext2d", "Element", "DomRect"] }
wasm-bindgen = "0.2"
tracing = "0.1"
common = { path = "../common" }
futures-channel = "0.3"
gloo-timers = { version = "0.3", features = ["futures"] }
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen = "0.6"
chrono = "0.4"
js-sys = "0.3"
