//! Artifact related enums.

use serde::{Deserialize, Serialize};
#[cfg(feature = "sqlx")]
use sqlx::Type;

/// Artifact source type.
///
/// Stored as an integer in the database while exposed as an enum in Rust/API DTOs.
/// `RemoteUrl` is reserved for future URL-backed artifacts and is not enabled by
/// the Batch 3.1 create flow yet.
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
#[cfg_attr(feature = "sqlx", derive(Type))]
#[cfg_attr(feature = "sqlx", sqlx(type_name = "INTEGER"))]
pub enum ArtifactSourceType {
    /// Existing Finance Attachment reference.
    #[default]
    Attachment = 1,
    /// Text content generated by Agent/runtime and stored as an artifact file.
    GeneratedContent = 2,
    /// Remote URL-backed artifact, reserved for future extension.
    RemoteUrl = 3,
}

impl ArtifactSourceType {
    /// Convert from i32.
    pub fn from_i32(v: i32) -> Self {
        match v {
            1 => Self::Attachment,
            2 => Self::GeneratedContent,
            3 => Self::RemoteUrl,
            _ => Self::default(),
        }
    }

    /// Convert to i32.
    pub fn to_i32(&self) -> i32 {
        *self as i32
    }
}

impl From<i32> for ArtifactSourceType {
    fn from(v: i32) -> Self {
        Self::from_i32(v)
    }
}

impl From<i64> for ArtifactSourceType {
    fn from(v: i64) -> Self {
        (v as i32).into()
    }
}

impl From<ArtifactSourceType> for i32 {
    fn from(source_type: ArtifactSourceType) -> i32 {
        source_type as i32
    }
}
