//! Runtime Tool Execution 具体实现

use common::error::{err, bail_err, Error, Result};
use crate::models::tool::{Tool, ToolExecutionResult};
use crate::pkg::request_context::RequestContext;
use crate::pkg::tool_tracing::entry::ToolCallEntry;
use crate::pkg::tool_tracing::logger::{ToolCallLogger, ToolCallQuery};
use crate::service::domain::runtime::{RuntimeDomainImpl, RuntimeToolExecution};
use common::enums::{ControlMode, ToolProtocol, ToolStatus};
use rig::tool::ToolError;
use serde_json::Value;

#[async_trait::async_trait]
impl RuntimeToolExecution for RuntimeDomainImpl {
    async fn call_tool_by_id(
        &self,
        ctx: RequestContext,
        tool_id: String,
        args: Value,
    ) -> Result<ToolExecutionResult> {
    let tool = self
        .tool_dal
        .get_by_id(ctx.clone(), tool_id.clone())
        .await?
        .ok_or_else(|| {
            common::error::Error::tool_call_failed(format!("Tool not found: {}", tool_id))
        })?;

        self.call_tool(ctx, &tool, args).await
    }

    async fn call_tool(
        &self,
        ctx: RequestContext,
        tool: &Tool,
        args: Value,
    ) -> Result<ToolExecutionResult> {
        let tool_id = tool.po.id.clone();
        ensure_tool_enabled(&tool_id, &tool.po.status)?;

        let execution = match tool.po.protocol {
            ToolProtocol::Mcp => self.mcp_tool_dal.call_tool(ctx, tool, args).await,
            ToolProtocol::Builtin | ToolProtocol::Http => {
                self.tool_dal.call_tool(ctx, tool, args).await
            }
        };

        let result = match execution {
            Ok(result) => result,
            Err(error) => {
                let mapped_message: String = match tool.po.protocol {
                    ToolProtocol::Mcp => map_mcp_tool_error(&tool_id, &error),
                    ToolProtocol::Builtin | ToolProtocol::Http => error.to_string(),
                };
                return Err(common::error::Error::new(
                    common::error::ErrorCode::ToolExecutionFailed,
                    mapped_message,
                ));
            }
        };
    
        // ToolCall entry is created by LoggingDecorator in tool_call_dal
        // We just need the tool_id for ToolExecutionResult, call_id is generated by the decorator
        // Wait, no: we need to get the entry that was created during the call...
        // Actually, looking back, the call returns (result, entry) in call_manual, but not in call.
        // In call, the entry is saved by the decorator, we just need to create the ToolExecutionResult.
        Ok(ToolExecutionResult::new(
            result,
            tool_id.clone(),
            uuid::Uuid::now_v7().to_string(),
        ))
    }

    async fn call_manual_tool_for_agent(
        &self,
        ctx: RequestContext,
        agent_id: String,
        tool_id: String,
        args: Value,
    ) -> Result<ToolExecutionResult> {
        let ctx = ctx.to_builder().agent_id(&agent_id).build();

        // 先从绑定工具中查找
        let bound_tools = self
            .tool_dal
            .list_tools_for_agent_full(ctx.clone(), &agent_id)
            .await?;

        let bound_tool = bound_tools
            .into_iter()
            .find(|tool| tool.po.id == tool_id);

        // 如果绑定工具中没有，检查是否是神经工具或已安装工具包
        let tool = match bound_tool {
            Some(tool) => tool,
            None => {
                let all_tools = self
                    .tool_dal
                    .query(
                        ctx.clone(),
                        crate::service::dao::tool::ToolQuery {
                            enabled_only: Some(true),
                            ..Default::default()
                        },
                    )
                    .await?;

                // 先尝试匹配神经工具
                let neural_tool = all_tools.iter().find(|t| {
                    t.po.id == tool_id && t.po.get_tags().contains(&"neural".to_string())
                }).cloned();

                if let Some(tool) = neural_tool {
                    tool
                } else {
                    // 再尝试匹配已安装工具包（tool 的 tags 与 agent 的 installed_tags 有交集）
                    let installed_tags = self
                        .agent_dal
                        .find_by_id(ctx.clone(), &agent_id)
                        .await?
                        .map(|agent| agent.po.get_installed_tags())
                        .unwrap_or_default();

                    if installed_tags.is_empty() {
                        return Err(common::error::Error::tool_call_failed(format!(
                            "Manual tool call denied: tool {} is not bound to agent {}, not a neural tool, and agent has no installed tool packs",
                            tool_id, agent_id
                        )));
                    }

                    all_tools
                        .into_iter()
                        .find(|t| {
                            if t.po.id != tool_id {
                                return false;
                            }
                            let tool_tags = t.po.get_tags();
                            installed_tags.iter().any(|installed| tool_tags.contains(installed))
                        })
                        .ok_or_else(|| {
                            common::error::Error::tool_call_failed(format!(
                                "Manual tool call denied: tool {} is not bound to agent {}, not a neural tool, and does not belong to any installed tool pack (installed: {:?})",
                                tool_id, agent_id, installed_tags
                            ))
                        })?
                }
            }
        };

        if tool.po.control_mode != ControlMode::Manual {
            let msg: String = format!(
                "Manual tool call denied: tool {} has control mode {:?}",
                tool_id, tool.po.control_mode
            );
            let msg: String = msg;
            return Err(common::error::Error::new(
                common::error::ErrorCode::ToolExecutionFailed,
                msg
            ));

        }

        self.call_tool(ctx, &tool, args).await
    }

    async fn query_tool_call_entries(
        &self,
        ctx: RequestContext,
        query: ToolCallQuery,
    ) -> Result<Vec<ToolCallEntry>> {
        let query = super::tool_call_query::with_context_scope(ctx, query)?;
        Ok(self.tool_call_logger
            .query_calls(query)?)
    }

    async fn get_tool_call_entry_by_id(
        &self,
        ctx: RequestContext,
        query: ToolCallQuery,
    ) -> Result<Option<ToolCallEntry>> {
        super::tool_call_query::ensure_call_id_present(&query)?;
        let query = super::tool_call_query::with_context_scope(ctx, query)?;
        let mut entries = self.tool_call_logger
            .query_calls(query)?;
        Ok(entries.pop())
    }
}

fn ensure_tool_enabled(tool_id: &str, status: &ToolStatus) -> Result<()> {
    if *status != ToolStatus::Enabled {
        bail_err!(ToolExecutionFailed, "Tool execution denied: tool {} has status {:?}", tool_id, status);
    }

    Ok(())
}

fn map_mcp_tool_error(tool_id: &str, error: &Error) -> String {
    let message = error.to_string();
    let normalized = message.to_lowercase();
    let safe_message = if normalized.contains("timed out") || normalized.contains("timeout") {
        format!("MCP tool call timed out for tool_id: {}", tool_id)
    } else if normalized.contains("server") && normalized.contains("not found") {
        format!("MCP server not found for tool_id: {}", tool_id)
    } else if normalized.contains("server") && normalized.contains("disabled") {
        format!("MCP server disabled for tool_id: {}", tool_id)
    } else if normalized.contains("tool") && normalized.contains("disabled") {
        format!("MCP tool disabled: {}", tool_id)
    } else if normalized.contains("tool") && normalized.contains("not found") {
        format!("MCP tool not found: {}", tool_id)
    } else {
        format!("MCP tool call failed for tool_id: {}", tool_id)
    };

    safe_message
}
