//! Runtime Tool Execution 具体实现

use common::error::{err, bail_err, Error, Result};
use crate::models::tool::{Tool, ToolExecutionResult};
use crate::pkg::request_context::RequestContext;
use crate::pkg::tool_tracing::entry::ToolCallEntry;
use crate::pkg::tool_tracing::logger::{ToolCallLogger, ToolCallQuery};
use crate::service::domain::runtime::{RuntimeDomainImpl, RuntimeToolExecution};
use common::enums::{ControlMode, ToolProtocol, ToolStatus};
use rig::tool::ToolError;
use serde_json::Value;

#[async_trait::async_trait]
impl RuntimeToolExecution for RuntimeDomainImpl {
    async fn call_tool_by_id(
        &self,
        ctx: RequestContext,
        tool_id: String,
        args: Value,
    ) -> Result<ToolExecutionResult> {
    let tool = self
        .tool_dal
        .get_by_id(ctx.clone(), tool_id.clone())
        .await?
        .ok_or_else(|| {
            common::error::Error::tool_call_failed(format!("Tool not found: {}", tool_id))
        })?;

        self.call_tool(ctx, &tool, args).await
    }

    async fn call_tool(
        &self,
        ctx: RequestContext,
        tool: &Tool,
        args: Value,
    ) -> Result<ToolExecutionResult> {
        let tool_id = tool.po.id.clone();
        ensure_tool_enabled(&tool_id, &tool.po.status)?;

        let execution = match tool.po.protocol {
            ToolProtocol::Mcp => self.mcp_tool_dal.call_tool(ctx, tool, args).await,
            ToolProtocol::Builtin | ToolProtocol::Http => {
                self.tool_dal.call_tool(ctx, tool, args).await
            }
        };

        let result = match execution {
            Ok(result) => result,
            Err(error) => {
                let mapped_message: String = match tool.po.protocol {
                    ToolProtocol::Mcp => map_mcp_tool_error(&tool_id, &error),
                    ToolProtocol::Builtin | ToolProtocol::Http => error.to_string(),
                };
                return Err(common::error::Error::new(
                    common::error::ErrorCode::ToolExecutionFailed,
                    mapped_message,
                ));
            }
        };
    
        // ToolCall entry is created by LoggingDecorator in tool_call_dal
        // We just need the tool_id for ToolExecutionResult, call_id is generated by the decorator
        // Wait, no: we need to get the entry that was created during the call...
        // Actually, looking back, the call returns (result, entry) in call_manual, but not in call.
        // In call, the entry is saved by the decorator, we just need to create the ToolExecutionResult.
        Ok(ToolExecutionResult::new(
            result,
            tool_id.clone(),
            uuid::Uuid::now_v7().to_string(),
        ))
    }

    async fn call_manual_tool_for_agent(
        &self,
        ctx: RequestContext,
        agent_id: String,
        tool_id: String,
        args: Value,
    ) -> Result<ToolExecutionResult> {
        let bound_tools = self
            .tool_dal
            .list_tools_for_agent_full(ctx.clone(), &agent_id)
            .await?;

        let tool = bound_tools
            .iter()
            .find(|tool| tool.po.id == tool_id)
            .ok_or_else(|| {
                common::error::Error::tool_call_failed(format!(
                    "Manual tool call denied: tool {} is not bound to agent {}",
                    tool_id, agent_id
                ))
            })?;

        if tool.po.control_mode != ControlMode::Manual {
            let msg: String = format!(
                "Manual tool call denied: tool {} has control mode {:?}",
                tool_id, tool.po.control_mode
            );
            let msg: String = msg;
            return Err(common::error::Error::new(
                common::error::ErrorCode::ToolExecutionFailed,
                msg
            ));

        }

        self.call_tool(ctx, tool, args).await
    }

    async fn query_tool_call_entries(
        &self,
        ctx: RequestContext,
        query: ToolCallQuery,
    ) -> Result<Vec<ToolCallEntry>> {
        let query = super::tool_call_query::with_context_scope(ctx, query)?;
        Ok(ToolCallLogger::get()
            .query_calls(query)?)
    }

    async fn get_tool_call_entry_by_id(
        &self,
        ctx: RequestContext,
        query: ToolCallQuery,
    ) -> Result<Option<ToolCallEntry>> {
        super::tool_call_query::ensure_call_id_present(&query)?;
        let query = super::tool_call_query::with_context_scope(ctx, query)?;
        let mut entries = ToolCallLogger::get()
            .query_calls(query)?;
        Ok(entries.pop())
    }
}

fn ensure_tool_enabled(tool_id: &str, status: &ToolStatus) -> Result<()> {
    if *status != ToolStatus::Enabled {
        bail_err!(ToolExecutionFailed, "Tool execution denied: tool {} has status {:?}", tool_id, status);
    }

    Ok(())
}

fn map_mcp_tool_error(tool_id: &str, error: &Error) -> String {
    let message = error.to_string();
    let normalized = message.to_lowercase();
    let safe_message = if normalized.contains("timed out") || normalized.contains("timeout") {
        format!("MCP tool call timed out for tool_id: {}", tool_id)
    } else if normalized.contains("server") && normalized.contains("not found") {
        format!("MCP server not found for tool_id: {}", tool_id)
    } else if normalized.contains("server") && normalized.contains("disabled") {
        format!("MCP server disabled for tool_id: {}", tool_id)
    } else if normalized.contains("tool") && normalized.contains("disabled") {
        format!("MCP tool disabled: {}", tool_id)
    } else if normalized.contains("tool") && normalized.contains("not found") {
        format!("MCP tool not found: {}", tool_id)
    } else {
        format!("MCP tool call failed for tool_id: {}", tool_id)
    };

    safe_message
}
